package propagationofexception;

public class Demo2 {
	void call2() {
	 new Demo3().divide();
		}

	}


